
services:
  audiomate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audiomate
    ports:
      - "8501:8501"
    volumes:
      - ./app/uploads:/app/uploads
      - whisper_cache:/root/.cache
    # —— GPU ————————————————————————————
    deploy:                               # funciona con `docker compose` o Swarm
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      - CUDA_LAUNCH_BLOCKING=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
    restart: unless-stopped

volumes:
  whisper_cache:
