
services:
  audiomate:
    build: .
    container_name: audiomate-gpu

    runtime: nvidia
    deploy:
      resources:
        limits:
          cpus: "12"
          memory: 32G
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

    environment:
      OMP_NUM_THREADS: "12"
      WHISPER_MODEL: large-v2
      WHISPER_COMPUTE_TYPE: float16
      WHISPER_FORCE_CPU: "0"

    volumes:
      - ./:/app:delegated
      - ./uploads:/uploads
      - whisper_cache:/root/.cache/whisper
      - torch_cache:/root/.cache/torch

    ports:
      - "8501:8501"
    shm_size: "2g"
    restart: unless-stopped

volumes:
  whisper_cache:
  torch_cache:
