# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show cwd & workflows folder
        run: |
          echo ">> pwd: $(pwd)"
          ls -R .github

      - name: List .github/workflows
        run: ls -R .github/workflows

      - name: Install system dependencies
        run: |
          echo "--- installing ffmpeg now ---"
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsndfile1
          echo "--- installed ffmpeg $(which ffprobe) ---"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests with coverage
        run: |
          pip install coverage codecov
          coverage run -m pytest --maxfail=1 --disable-warnings -q
          coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
